const mongoose = require("mongoose");
const timetableschema = new mongoose.Schema({
  class: {
    type: String,
    require: true,
  },
  batch: {
    type: String,
    required: true,
  },
  section: {
    type: String,
    required: true,
  },
  semester: {
    type: Number,
    required: true,
  },
  timetable: [
    {
      Monday: [
        {
          courseName: {
            type: String,
            required: true,
            enum: [
              "Introduction to ICT",
              "English Comprehension and Composition",
              "Islamic Studies",
              "Calculus and Analytical Geometry",
              "Applied Physics for Engineers",
              "Discrete Structures",
              "Programming Fundamentals",
              "Professional Practices for IT",
              "Report Writing Skills",
              "Multivariable Calculus",
              "Electricity, Magnetism and Optics",
              "Object Oriented Programming",
              "Digital Logic Design",
              "Pakistan Studies",
              "Linear Algebra",
              "Statistics and Probability Theory",
              "Modern Physics",
              "Data Structures and Algorithms",
              "Software Engineering Concepts",
              "Microprocessor and Assembly Language",
              "Database Systems I",
              "Communication Skills",
              "Differential Equations",
              "Design and Analysis of Algorithms",
              "Operating Systems",
              "Data Communications and Computer Networks",
              "Numerical Computing",
              "Theory of Automata",
              "Web Technologies",
              "Artificial Intelligence",
              "Human Computer Interaction",
              "Compiler Construction",
              "Computer Architecture",
              "Mobile Application Development",
              "Software Project Management",
              "Game Development",
              "Computational Intelligence",
              "Introduction to Data Science",
              "Data Warehousing and Data Mining",
              "Digital Image Processing",
              "Computer Graphics",
              "Machine Learning",
              "Computer Vision",
              "Introduction to Management",
              "Introduction to Psychology",
              "--",
            ],
          },
          classTime: {
            type: String,
            required: true,
          },
          classRoom: {
            type: String,
            required: true,
          },
          slot: {
            type: String,
            required: true,
            enum: ["M1", "M2", "M3", "M4", "M5", "M6"],
          },
        },
      ],
      Tuesday: [
        {
          courseName: {
            type: String,
            require: true,
            enum: [
              "Introduction to ICT",
              "English Comprehension and Composition",
              "Islamic Studies",
              "Calculus and Analytical Geometry",
              "Applied Physics for Engineers",
              "Discrete Structures",
              "Programming Fundamentals",
              "Professional Practices for IT",
              "Report Writing Skills",
              "Multivariable Calculus",
              "Electricity, Magnetism and Optics",
              "Object Oriented Programming",
              "Digital Logic Design",
              "Pakistan Studies",
              "Linear Algebra",
              "Statistics and Probability Theory",
              "Modern Physics",
              "Data Structures and Algorithms",
              "Software Engineering Concepts",
              "Microprocessor and Assembly Language",
              "Database Systems I",
              "Communication Skills",
              "Differential Equations",
              "Design and Analysis of Algorithms",
              "Operating Systems",
              "Data Communications and Computer Networks",
              "Numerical Computing",
              "Theory of Automata",
              "Web Technologies",
              "Artificial Intelligence",
              "Human Computer Interaction",
              "Compiler Construction",
              "Computer Architecture",
              "Mobile Application Development",
              "Software Project Management",
              "Game Development",
              "Computational Intelligence",
              "Introduction to Data Science",
              "Data Warehousing and Data Mining",
              "Digital Image Processing",
              "Computer Graphics",
              "Machine Learning",
              "Computer Vision",
              "Introduction to Management",
              "Introduction to Psychology",
              "--",
            ],
          },
          classTime: {
            type: String,
            required: true,
          },
          classRoom: {
            type: String,
            required: true,
          },
          slot: {
            type: String,
            required: true,
            enum: ["T1", "T2", "T3", "T4", "T5", "T6"],
          },
        },
      ],
      Wednesday: [
        {
          courseName: {
            type: String,
            require: true,
            enum: [
              "Introduction to ICT",
              "English Comprehension and Composition",
              "Islamic Studies",
              "Calculus and Analytical Geometry",
              "Applied Physics for Engineers",
              "Discrete Structures",
              "Programming Fundamentals",
              "Professional Practices for IT",
              "Report Writing Skills",
              "Multivariable Calculus",
              "Electricity, Magnetism and Optics",
              "Object Oriented Programming",
              "Digital Logic Design",
              "Pakistan Studies",
              "Linear Algebra",
              "Statistics and Probability Theory",
              "Modern Physics",
              "Data Structures and Algorithms",
              "Software Engineering Concepts",
              "Microprocessor and Assembly Language",
              "Database Systems I",
              "Communication Skills",
              "Differential Equations",
              "Design and Analysis of Algorithms",
              "Operating Systems",
              "Data Communications and Computer Networks",
              "Numerical Computing",
              "Theory of Automata",
              "Web Technologies",
              "Artificial Intelligence",
              "Human Computer Interaction",
              "Compiler Construction",
              "Computer Architecture",
              "Mobile Application Development",
              "Software Project Management",
              "Game Development",
              "Computational Intelligence",
              "Introduction to Data Science",
              "Data Warehousing and Data Mining",
              "Digital Image Processing",
              "Computer Graphics",
              "Machine Learning",
              "Computer Vision",
              "Introduction to Management",
              "Introduction to Psychology",
              "--",
            ],
          },
          classTime: {
            type: String,
            required: true,
          },
          classRoom: {
            type: String,
            required: true,
          },
          slot: {
            type: String,
            required: true,
            enum: ["W1", "W2", "W3", "W4", "W5", "W6"],
          },
        },
      ],
      Thursday: [
        {
          courseName: {
            type: String,
            require: true,
            enum: [
              "Introduction to ICT",
              "English Comprehension and Composition",
              "Islamic Studies",
              "Calculus and Analytical Geometry",
              "Applied Physics for Engineers",
              "Discrete Structures",
              "Programming Fundamentals",
              "Professional Practices for IT",
              "Report Writing Skills",
              "Multivariable Calculus",
              "Electricity, Magnetism and Optics",
              "Object Oriented Programming",
              "Digital Logic Design",
              "Pakistan Studies",
              "Linear Algebra",
              "Statistics and Probability Theory",
              "Modern Physics",
              "Data Structures and Algorithms",
              "Software Engineering Concepts",
              "Microprocessor and Assembly Language",
              "Database Systems I",
              "Communication Skills",
              "Differential Equations",
              "Design and Analysis of Algorithms",
              "Operating Systems",
              "Data Communications and Computer Networks",
              "Numerical Computing",
              "Theory of Automata",
              "Web Technologies",
              "Artificial Intelligence",
              "Human Computer Interaction",
              "Compiler Construction",
              "Computer Architecture",
              "Mobile Application Development",
              "Software Project Management",
              "Game Development",
              "Computational Intelligence",
              "Introduction to Data Science",
              "Data Warehousing and Data Mining",
              "Digital Image Processing",
              "Computer Graphics",
              "Machine Learning",
              "Computer Vision",
              "Introduction to Management",
              "Introduction to Psychology",
              "--",
            ],
          },
          classTime: {
            type: String,
            required: true,
          },
          classRoom: {
            type: String,
            required: true,
          },
          slot: {
            type: String,
            required: true,
            enum: ["Th1", "Th2", "Th3", "Th4", "Th5", "Th6"],
          },
        },
      ],
      Friday: [
        {
          courseName: {
            type: String,
            require: true,
            enum: [
              "Introduction to ICT",
              "English Comprehension and Composition",
              "Islamic Studies",
              "Calculus and Analytical Geometry",
              "Applied Physics for Engineers",
              "Discrete Structures",
              "Programming Fundamentals",
              "Professional Practices for IT",
              "Report Writing Skills",
              "Multivariable Calculus",
              "Electricity, Magnetism and Optics",
              "Object Oriented Programming",
              "Digital Logic Design",
              "Pakistan Studies",
              "Linear Algebra",
              "Statistics and Probability Theory",
              "Modern Physics",
              "Data Structures and Algorithms",
              "Software Engineering Concepts",
              "Microprocessor and Assembly Language",
              "Database Systems I",
              "Communication Skills",
              "Differential Equations",
              "Design and Analysis of Algorithms",
              "Operating Systems",
              "Data Communications and Computer Networks",
              "Numerical Computing",
              "Theory of Automata",
              "Web Technologies",
              "Artificial Intelligence",
              "Human Computer Interaction",
              "Compiler Construction",
              "Computer Architecture",
              "Mobile Application Development",
              "Software Project Management",
              "Game Development",
              "Computational Intelligence",
              "Introduction to Data Science",
              "Data Warehousing and Data Mining",
              "Digital Image Processing",
              "Computer Graphics",
              "Machine Learning",
              "Computer Vision",
              "Introduction to Management",
              "Introduction to Psychology",
              "--",
            ],
          },
          classTime: {
            type: String,
            required: true,
          },
          classRoom: {
            type: String,
            required: true,
          },
          slot: {
            type: String,
            required: true,
            enum: ["F1", "F2", "F3", "F4", "F5", "F6"],
          },
        },
      ],
    },
  ],
});
//create the collection in database
const Timetable = mongoose.model("Timetable", timetableschema);
module.exports = Timetable;
